-- TUJUAN: Mencari orang yang punya cucu tapi tidak punya cicit.

WITH HP AS
	(SELECT HASPARENT.ID,
			KID_ID,
			NAME
		FROM
			(SELECT MOTHERID ID,
					ID KID_ID
				FROM PEOPLE
				WHERE MOTHERID IS NOT NULL
				UNION SELECT FATHERID ID,
					ID KID_ID
				FROM PEOPLE
				WHERE FATHERID IS NOT NULL) HASPARENT
		LEFT JOIN PEOPLE P ON P.ID = HASPARENT.ID
		ORDER BY KID_ID DESC)

SELECT P.ID FIRST_GEN_ID,
	P.NAME FIRST_GEN_NAME,
	HP1.ID SEC_GEN_ID,
	HP1.NAME SEC_GEN_NAME,
	HP2.KID_ID THIRD_GEN_ID,
	HP3.KID_ID FOURTH_GEN_ID
FROM PEOPLE P
JOIN HP HP1 ON HP1.ID = P.ID
JOIN HP HP2 ON HP2.ID = HP1.KID_ID
LEFT JOIN HP HP3 ON HP2.KID_ID = HP3.ID
WHERE HP3.ID IS NULL;
