-- Tantangannya: Cari orang tua yang ternyata adalah anak tunggal.

WITH CTE AS
	(SELECT MOTHERID AS ID_ORTU,
			COUNT(MOTHERID)
		FROM PEOPLE
		GROUP BY MOTHERID
		HAVING COUNT(MOTHERID) = 1
		UNION SELECT FATHERID AS ID_ORTU,
			COUNT(FATHERID)
		FROM PEOPLE
		GROUP BY FATHERID
		HAVING COUNT(FATHERID) = 1),
	ALL_PARENTS AS
	(SELECT MOTHERID AS ID_ORTU
		FROM PEOPLE
		UNION SELECT FATHERID AS ID_ORTU
		FROM PEOPLE)
		
SELECT ID,
	NAME
FROM PEOPLE
WHERE (MOTHERID IN
		(SELECT ID_ORTU
			FROM CTE)
	OR FATHERID IN
		(SELECT ID_ORTU
			FROM CTE))
	AND ID IN
		(SELECT ID_ORTU
			FROM ALL_PARENTS);
